### ISSUE TITLE
Getting error after adding key in ubuntu 22.04

### ISSUE THREAD

**Issue by ZayRTun** [antares-sql/antares-ppa#1]
https://antares-sql.github.io/antares-ppa/./InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Comment by Fabio286** [comment]
Hi Zayar,

thanks for the report, i will update the installation script to avoid this warning.

**Comment by Fabio286** [comment]
I updated the installation script.
In your case to fix this warning run:

```shell
cd /etc/apt
sudo cp trusted.gpg trusted.gpg.d
```
